# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'basic2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "SnapKit"
  pod 'Kingfisher'
  pod 'PromiseKit'
  pod 'Alamofire'
  pod 'RxSwift'

  # Pods for basic2

end
